# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Publish an input docker image to the AWS ECR

on:
  workflow_dispatch:
    inputs:
      in_container:
        required: true
      out_container:
        required: true

# job definition
jobs:
  Build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job steps
    steps:
      # pull a docker image
      - name: pull a image to work with
        id: pull-it
        run: docker pull containers.renci.org/eds/${{ github.event.inputs.in_container }}

      # list the images for confirmation
      - name: list images 1
        run: docker images

      # push the image to AWS/ECR
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          local-image: containers.renci.org/eds/${{ github.event.inputs.in_container }}
          image: {{ github.event.inputs.out_container }}
