# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Test publish a docker image to AWS ECR

on: workflow_dispatch

# job definition
jobs:
  Build-and-publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job steps
    steps:
      # pull a docker image
      - name: pull a image to work with
        id: pull-it
        run: docker pull containers.renci.org/eds/apsviz-settings:latest

      - name: list images 1
        run: docker images
        
      - name: tag the image
        id: tag-it
        run: docker tag containers.renci.org/eds/apsviz-settings:latest 732457422609.dkr.ecr.us-east-2.amazonaws.com/apsviz-test:test

      - name: list images 2
        run: docker images
        
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          image: apsviz-test:test
