# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Build and publish the docker image

# trigger event is publishing a release in the repo (or a manual launch)
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false
        default: ''

  release:
    types: [published]

# working parameters that are specific to this script
env:
  REGISTRY: containers.renci.org/eds/apsviz-archiver

# job definition
jobs:
  pylint-build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # job steps
    steps:

      # get the tag for the image if passed in
      - name: Get the manually entered version
        if: ${{ github.event.inputs.version != '' }}
        run: |
          echo "VERSION=${ ${{ github.event.inputs.version_tag }} }" >> $GITHUB_OUTPUT

      # get the tag for the image if passed in
      - name: Get the manually entered version
        if: ${{ github.event.inputs.version == '' }}
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      # checkout the codebase
      - name: Checkout
        uses: actions/checkout@v1

      # connect to the renci image registry
      - name: Login to containers.renci.org
        uses: docker/login-action@v2
        with:
          registry: containers.renci.org
          username: ${{ secrets.USER }}
          password: ${{ secrets.PW }}


      # build and push the image. The docker v3 action automatically handles the git checkout.
      - name: Build/Push the image to the registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}:latest
            ${{ env.REGISTRY }}:${{ steps.get_version.outputs.VERSION }}
