# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

name: Pylint and pytest the repo codebase

on:
  push:
    branches:
    - main

jobs:
  lint:
    name: Execute pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build docker image
        run: docker build -t archiver-testing -f Dockerfile.test .

      - name: Run linter and get output
        run: |
          echo 'LINT_OUTPUT<<EOF' >> $GITHUB_ENV
          echo "$(docker run archiver-testing pylint --rcfile=.pylintrc --recursive=y ./)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

  test:
    name: Execute pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build
        run: docker build -t archiver-testing -f Dockerfile.test .

      - name: Run tests and get output
        run: |
          echo 'TEST_OUTPUT<<EOF' >> $GITHUB_ENV
          echo "$(docker run archiver-testing pytest --cov)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Exit if there are any test failures
        run: '[[ $TEST_OUTPUT != *FAILED* ]]'
